src/chat/urls.py
from django.urls import path, re_path
from . import views
from .views import ThreadView
urlpatterns = [
    path('', views.essai_index, name='essai_index'),
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('logout/', views.logout_page, name='logout'),
    path('search/', views.search_page, name='search'),
    path('add-friend/<int:id>/', views.send_friend_request, name='send'),
    path('accept-friend/<int:id>/', views.accept_friend_request, name='accept'),
    path('delete-friend_request/<int:id>/', views.delete_friend_request, name='delete'),
    #re_path(r"^(?P<username>[\w.@+-]+)", views.ThreadView, name='Thread'),
    re_path(r"^messages/(?P<username>[\w.@+-]+)/$", ThreadView.as_view(), name='messages'),
]

src/chatapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

src/chat/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models import Q
# Create your models here.

class Friend(models.Model): 
	users = models.ManyToManyField(User)
	current_user = models.ForeignKey(User, related_name='owner', null=True, on_delete='CASCADE')
	
class FriendRequest(models.Model):
	to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete='CASCADE', related_name='to_user')
	from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete='CASCADE', related_name='from_user')
	timestamp = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return "From {}, to {}".format(self.from_user.username,self.to_user.username)


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

src/chat/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class LoginForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password_first = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_again = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = self.cleaned_data
        password_one = self.cleaned_data.get('password_first')
        password_two = self.cleaned_data.get('password_again')
        if password_one != password_two:
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("The username you've chosen is unavailable.")
        return username

    def clean_email(self):
        email_address = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email_address)
        if qs.exists():
            raise forms.ValidationError("The email address you've chosen is already registered.")
        return email_address


class SearchForm(forms.Form):
    username = forms.CharField()

class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

src/chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout, get_user_model
from chat.forms import LoginForm, RegisterForm,  ComposeForm 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.conf import settings

from .models import FriendRequest, Friend, Thread, ChatMessage
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView



User = get_user_model()

# Create your views here.
@login_required(login_url='/login/')
def essai_index(request):
    friend = Friend.objects.filter(current_user=request.user).first()
    friend_list = friend.users.all().exclude(id=request.user.id) if friend else []

    fr=FriendRequest.objects.filter(to_user=request.user)
    frr = FriendRequest.objects.filter(from_user=request.user)

    return render(request, 'chat/essai_index.html', {'fr':fr, 'friend':friend_list, 'frr':frr })


def login_page(request):
    form = LoginForm(request.POST or None)
    context = {
        'form': form
    }
    print(request.user.is_authenticated)
    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            print("error.......")

    return render(request, "auth/login.html", context=context)

def register_page(request):
    form = RegisterForm(request.POST or None)
    context = {
        'form': form,
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password_first")
        new_user = User.objects.create_user(username, email, password)
    return render(request, "auth/register.html", context=context)

def logout_page(request):
    print(request)
    logout(request)
    return redirect('/')


def search_page(request):
    friend = Friend.objects.filter(current_user=request.user).first()
    friend_list = friend.users.all().exclude(id=request.user.id) if friend else []

    fr=FriendRequest.objects.filter(to_user=request.user)
    frr = FriendRequest.objects.filter(from_user=request.user)
    if request.method=='POST' :
        srch=request.POST['srh']
        if srch:
            match = User.objects.filter(Q(username__contains=srch)).exclude(id=request.user.id)
            #match = User.objects.filter(username=srch)
            if match.exists():
                print({'sr':match, 'fr':fr, 'friend':friend_list})
                return render(request,"search.html", {'sr':match, 'fr':fr, 'friend':friend_list, 'frr':frr })
            else:
                messages.error(request,'no result found')
        else:
            return redirect('/search/')
    
    return render(request,'search.html',{'fr':fr, 'friend':friend_list, 'frr':frr})


def send_friend_request(request, id):
    if request.user.is_authenticated:
        user = get_object_or_404(User, id=id)
        frequest, created = FriendRequest.objects.get_or_create(
            from_user=request.user,
            to_user=user)
        return redirect('/search/')


def cancel_friend_request(request, id):
    if request.user.is_authenticated:
        user = get_object_or_404(User, id=id)
        frequest = FriendRequest.objects.filter(
            from_user=request.user,
            to_user=user).first()
        frequest.delete()
        return redirect('/search/')


def accept_friend_request(request, id):
    #from_user = get_object_or_404(User, id=id)
    frequest = FriendRequest.objects.filter(id=id).first()
    user1 = request.user
    user2 = frequest.from_user
    friend1, created = Friend.objects.get_or_create(current_user=user1)
    friend2, created = Friend.objects.get_or_create(current_user=user2)
    #user1.profile.friends.add(user2.profile)
    #user2.profile.friends.add(user1.profile)
    friend1.users.add(user2)
    friend2.users.add(user1)

    frequest.delete()
    return redirect('/search/')


def delete_friend_request(request, id):
    #from_user = get_object_or_404(User, id=id)
    frequest = FriendRequest.objects.filter(id=id).first()
    frequest.delete()
    return redirect('/search/')


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

src/chat/templates/chat/essai_index.html
{% extends "base.html" %}

{% block content %}
<hr class="sidebar-divider my-0">
 <li class="nav-item active">
        <a class="nav-link" href="index.html">
          <span>Friends</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->

      <!-- Nav Item - Pages Collapse Menu -->
    {% if friend %}
    {% for r in friend %}
    <li class="nav-item">
          <a class="nav-link " href="{% url 'messages' username=r.username %}" >
        <span> {{r}} </span>
        </a> 
      </li>
    {% endfor %}
  {% endif %}
      

    
      <!-- Divider -->
   

      <!-- Heading -->
      

    
<hr class="sidebar-divider my-0">
 <li class="nav-item active">
        <a class="nav-link" href="index.html">
          <span>Friend Requests</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Received
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
    {% if fr %}
    {% for r in fr %}
    <li class="nav-item">

      <a class="nav-link " href="{% url 'accept' r.id %}" >
        
        <span> accept {{r.from_user}} </span> 
      </a> 
      <a class="nav-link " href="{% url 'delete' r.id %}" >
        
        <span> delete {{r.from_user}} </span> 
      </a> 

    </li>

    {% endfor %}
  {% endif %}
              
      

      <!-- Nav Item - Utilities Collapse Menu -->

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Sent
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      {% if frr %}
    {% for r in frr %}
    <li class="nav-item">

      <a class="nav-link " href="{% url 'accept' r.id %}" >
        
        <span> cancel {{r.to_user}} </span> 
      </a> 

    </li>

    {% endfor %}
  {% endif %}
              

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          

          <!-- Topbar Search -->
        
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="post" action="/search/" >
            {% csrf_token %}

            <div class="input-group">
              <input type="text" name="srh" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              
                  <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
             
            </li>


<div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        {% if user.is_authenticated %}
        <a class="nav-link dropdown-toggle" href="{% url 'logout' %}" >
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">logout</span>
        </a>
        {% else %}
        <a class="nav-link dropdown-toggle" href="{% url 'login' %}" >
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">login</span>
        </a>
              
       {% endif %}
       

              <!-- Dropdown - User Information -->
              
    </li>

  </ul>

</nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
            <h1 class="h3 mb-0 text-gray-800">let's start chatting</h1>

          </div>
  
{% endblock %}

src/chat/templates/chat/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

src/chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
<hr class="sidebar-divider my-0">
 <li class="nav-item active">
        <a class="nav-link" href="index.html">
          <span>Friends</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->

      <!-- Nav Item - Pages Collapse Menu -->
   
		<li class="nav-item">
        	<a class="nav-link " href="#" >
				      <span>
                 amin12 
              </span>
	    	  </a> 
	   </li>
	   <li class="nav-item">
          <a class="nav-link " href="#" >
              <span>
                 hanane 
              </span>
          </a> 
     </li>
     <li class="nav-item">
          <a class="nav-link " href="#" >
              <span>
                 hassan 
              </span>
          </a> 
     </li>
     <li class="nav-item">
          <a class="nav-link " href="#" >
              <span>
                 ali 
              </span>
          </a> 
     </li>
     <li class="nav-item">
          <a class="nav-link " href="#" >
              <span>
                 oussama
              </span>
          </a> 
     </li>

    
      <!-- Divider -->
   

      <!-- Heading -->
      

    
<hr class="sidebar-divider my-0">
 <li class="nav-item active">
        <a class="nav-link" href="index.html">
          <span>Friend Requests</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Received
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
    {% if fr %}
		{% for r in fr %}
		<li class="nav-item">

			<a class="nav-link " href="#" >
				
				<span> accept {{r.from_user}} </span> 
			</a> 

		</li>

		{% endfor %}
	{% endif %}
              
      

      <!-- Nav Item - Utilities Collapse Menu -->

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Sent
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
     
		<li class="nav-item">

			<a class="nav-link " href="#" >
				
				<span> cancel alae-eddine </span> 
			</a> 

		</li>


    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          

          <!-- Topbar Search -->
        
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="post" action="/search/" >
            {% csrf_token %}

            <div class="input-group">
              <input type="text" name="srh" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              
                  <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
             
            </li>


<div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        {% if user.is_authenticated %}
        <a class="nav-link dropdown-toggle" href="{% url 'logout' %}" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">logout</span>
        </a>
        {% else %}
        <a class="nav-link dropdown-toggle" href="{% url 'login' %}" id="userDropdown" role="data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        	<span class="mr-2 d-none d-lg-inline text-gray-600 small">login</span>
        </a>
              
     	 {% endif %}
     	 

              <!-- Dropdown - User Information -->
              
    </li>

  </ul>

</nav>

<div class="container-fluid">

          <!-- Page Heading -->   
<div class="d-sm-flex align-items-center justify-content-between mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    <h1 class="h3 mb-0 text-gray-800">Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %} </h1>
</div>
<br><br>


<ul id='chat-items'>
{% for chat in object.chatmessage_set.all %}

<li><h6 style="color:black;">{{ chat.user }} :</h6>  {{ chat.message }}  </li>

{% endfor %}
</ul>


<form id='form' method='POST'> {% csrf_token %}
{{form.as_p }}
<input type='submit' class='btn btn-primary'/>
</form>

{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>

<script>
// websocket scripts
//console.log(window.location)
var loc = window.location
var formData = $("#form")
var msgInput = $("#id_message")
var chatHolder = $("#chat-items")


var wsStart = 'ws://'
if(loc.protocol == 'https:'){
	wsStart = 'wss://'
}

var endpoint = wsStart + loc.host + loc.pathname + "/" 
//console.log(endpoint)
var socket = new ReconnectingWebSocket(endpoint)

socket.onmessage = function(e){
	console.log("message", e)
	var msgText = msgInput.val()
	var chatDataMsg = JSON.parse(e.data)
	/*chatHolder.append("<li>"+ chatDataMsg.message + " via " + chatDataMsg.username "</li>") */
	
	chatHolder.append("<li> <h6 style='color:black;'>"+ chatDataMsg.username +" :</h6>"  + chatDataMsg.message +"</li>")
}
socket.onopen = function(e){
	console.log("open", e)
	formData.submit(function(event){
		event.preventDefault()
		var msgText = msgInput.val()
		var finalData ={
			'message': msgText
		}
		socket.send(JSON.stringify(finalData))
		formData[0].reset()
		
	})
	
}

socket.onerror = function(e){
	console.log("error", e)
}
socket.onclose = function(e){
	console.log("close", e)
}

</script>
{% endblock %}